services:
  chat-copilot:
    build: ../.
    image: chat-copilot
    container_name: chat-copilot
    volumes:
      - ./data:/data
      - ${WECHAT_PATH}
    command:
      - api
      - crontab
    ports:
      - "6978:6978"
  # mysql:
  #   image: mysql:9.0
  #   command: --default-authentication-plugin=mysql_native_password
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
  #     - MYSQL_DATABASE=${MYSQL_DATABASE}
  #     - MYSQL_USER=${MYSQL_USER}
  #     - MYSQL_PASSWORD=${MYSQL_PASSWORD}
  #   volumes:
  #     - ./data/mysql:/var/lib/mysql
  #   ports:
  #     - "3306:3306"
  # redis:
  #   image: "redis:7-alpine"
  #   command: "redis-server --requirepass ${REDIS_PASSWORD}"
  #   volumes:
  #     - ./data/redis:/data
  #   ports:
  #     - "6379:6379"
