name: Release

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4
        with:
          show-progress: true
          submodules: true

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.21.x"

      - name: Install dependencies
        run: |
          brew update
          brew install make

      - name: Debug - List files
        run: |
          echo "Current directory: $(pwd)"
          echo "List of files:"
          ls -la

      - name: Debug - List files in pkg/audio
        run: |
          echo "List of files in pkg/audio:"
          ls -la ./pkg/audio

      - name: Build C binary
        run: |
          cd ./pkg/audio/slik
          make

      - name: Build go binary
        run: |
          CGO_ENABLED=1 GOARCH=arm64 go build -v -o chat-copilot_arm64 ./cmd/...
          CGO_ENABLED=1 GOARCH=amd64 go build -v -o chat-copilot_amd64 ./cmd/...
